services:
  - type: web
    name: que-hay-en-tu-plato
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    plan: free 